# Generated by Django 6.0.6 on 2026-06-07 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmail_message_id', models.CharField(max_length=255, unique=True)),
                ('sender', models.CharField(max_length=500)),
                ('sender_name', models.CharField(blank=True, max_length=255)),
                ('receiver', models.CharField(blank=True, max_length=500)),
                ('subject', models.TextField(blank=True)),
                ('body', models.TextField(blank=True)),
                ('body_html', models.TextField(blank=True)),
                ('received_at', models.DateTimeField()),
                ('has_attachments', models.BooleanField(default=False)),
                ('attachment_names', models.JSONField(default=list)),
                ('is_processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['user', 'received_at'], name='gmail_sync__user_id_29cfbf_idx'), models.Index(fields=['user', 'is_processed'], name='gmail_sync__user_id_3aec69_idx')],
            },
        ),
    ]
