# Generated by Django 6.0.6 on 2026-06-07 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gmail_sync', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('Job', 'Job'), ('Internship', 'Internship'), ('Funding', 'Funding'), ('AI', 'AI'), ('Startup', 'Startup'), ('Security', 'Security'), ('Event', 'Event'), ('Personal', 'Personal'), ('Promotion', 'Promotion'), ('Other', 'Other')], default='Other', max_length=50)),
                ('priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Low', max_length=20)),
                ('deadline', models.CharField(blank=True, max_length=255)),
                ('important_points', models.JSONField(default=list)),
                ('links', models.JSONField(default=list)),
                ('keyword_matches', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='gmail_sync.email')),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['keyword'],
                'unique_together': {('user', 'keyword')},
            },
        ),
    ]
