# Generated by Django 6.0.6 on 2026-06-10 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_processor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailanalysis',
            name='action_items',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='emailanalysis',
            name='action_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emailanalysis',
            name='reply_subject',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='emailanalysis',
            name='sender_verification',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='emailanalysis',
            name='sender_verified',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='emailanalysis',
            name='sentiment',
            field=models.CharField(default='Neutral', max_length=20),
        ),
        migrations.AddField(
            model_name='emailanalysis',
            name='suggested_reply',
            field=models.TextField(blank=True),
        ),
    ]
